--- #YAML:1.0
name: CGI-Application-Framework
version: 0.22
author:
  - Richard Dice <rdice@pobox.com>
abstract: Fully-featured MVC web application platform
license: perl
generated_by: Module::Build version 0.2602, without YAML.pm
